version: "3.8"
services:
  web:
    build:
      context: .
      labels:
        commit: "${COMMIT}"
    image: speaki
    env_file:
      - .env
    command: /web
    ports:
      - 8080:8080
    volumes:
      - media:/media
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
  redis:
    image: redis:6.2.6-alpine
    command: redis-server --appendonly yes
    volumes:
      - rdb_data:/data
    ports:
      - 6379:6379

  worker:
    image: speaki:latest
    command: /worker
    environment:
      - WORKER=1
    depends_on:
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes:
      - media:/media
    env_file:
      - .env

  mysql:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "speaki"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=mysql --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 5s
      retries: 10


volumes:
  rdb_data:
  mysql_data:
  media:
