name: Create and publish a Docker image

on:
  push:
    branches:
    - dev
    - release/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.compute-docker-tag.outputs.tag }}
      target_tag: ${{ steps.compute-docker-tag.outputs.target_tag }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/compute-docker-tag
        id: compute-docker-tag

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          build-args: |
            BUILD_VERSION=${{ needs.tag.outputs.tag }}
            BUILD_COMMIT=${{ github.sha }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend_core:${{ needs.tag.outputs.tag }}
